// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SHOP.Model
{
    public partial class CommonCode2
    {
        [Key]
        [Column(Order =1)]
        public string Code1 { get; set; }
        [Key]
        [Column(Order = 2)]
        public string Code2 { get; set; }
        public string Name { get; set; }
    }
}