// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SHOP.Model
{
    public partial class CommonCode1
    {
        [Key]
        public string Code1 { get; set; }
        public string Name { get; set; }
    }
}