// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SHOP.Model
{
    public partial class CommonCode1
    {
        [Key]
        public string Com1Code1 { get; set; }
        public string Com1Name { get; set; }

        public virtual ICollection<Product> products { get; set; }


    }
}