// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SHOP.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ComModel
{
    public partial class Product
    {
        [Key]
        public int Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }

        public virtual ICollection<Cart> Carts { get; set; }
    }
}